### ISSUE TITLE
Make $upstream_* variables meaningful

### ISSUE THREAD

**Issue by nybus** [tarantool/nginx_upstream_module#121] opened 2019-04-15 15:13 UTC
Specifically
```
$upstream_response_time
$upstream_status
$upstream_addr
```
nginx.conf:
`log_format main ... 'rt=$request_time urt=$upstream_response_time us=$upstream_status u="$upstream_addr"';`

access.log:
`rt=0.010 urt=- us=- u="-"`

**Comment by dedok** [comment] 2019-04-15 18:46
Hi,

Can't reproduce this.

NGINX version: 1.15.11
I used following configuration:
```
http {                                                                                                                                                          
    log_format main 'rt=$request_time urt=$upstream_response_time us=$upstream_status u="$upstream_addr"';
                                              
    server {                                                                                                                                     
      location / {                                                            
       tnt_pass tnt;
       access_log log/echo.log main;                                                        
    }
}                  
```

**Comment by dedok** [comment] 2019-06-03 08:41
Hi,

I closed this, since this bug can't be reproduces, if you still have this issue, then please re-open this one.

Thanks!

**Closed by dedok** 2019-06-03 08:41 UTC
Labels: question
